spring:
  application:
    name: service02

eureka:
  client:
    #registerWithEureka: false
    #fetchRegistry: false
    serviceURL:
      defaultZone: http://localhost:1111/eureka/
  instance:
    preferIpAddress: true
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 100
    leaseExpirationDurationInSeconds: 200
server:
  port: 8085